name:                availer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/marcosh/availer#readme
license:             BSD3
author:              Marco Perone
maintainer:          pasafama@gmail.com
copyright:           2019 Marco Perone
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - either
  - lens

library:
  source-dirs:       src

tests:
  availer-test:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - availer
      - hspec
      - QuickCheck
